export const INDIAN_UNIVERSITIES: string[] = [
  'Indian Institute of Technology (IIT) Delhi',
  'Indian Institute of Technology (IIT) Bombay',
  'Indian Institute of Technology (IIT) Madras',
  'Indian Institute of Technology (IIT) Kanpur',
  'Indian Institute of Technology (IIT) Kharagpur',
  'Indian Institute of Technology (IIT) Roorkee',
  'Indian Institute of Technology (IIT) Guwahati',
  'Indian Institute of Technology (IIT) Hyderabad',
  'Indian Institute of Technology (IIT) Indore',
  'Indian Institute of Technology (IIT) Patna',
  'Indian Institute of Technology (IIT) BHU Varanasi',
  'Indian Institute of Technology (IIT) ISM Dhanbad',
  'Indian Institute of Technology (IIT) Bhubaneswar',
  'Indian Institute of Technology (IIT) Gandhinagar',
  'Indian Institute of Technology (IIT) Jodhpur',
  'Indian Institute of Technology (IIT) Mandi',
  'Indian Institute of Technology (IIT) Palakkad',
  'Indian Institute of Technology (IIT) Tirupati',
  'Indian Institute of Technology (IIT) Goa',
  'National Institute of Technology (NIT) Tiruchirappalli',
  'National Institute of Technology (NIT) Surathkal',
  'National Institute of Technology (NIT) Warangal',
  'National Institute of Technology (NIT) Rourkela',
  'National Institute of Technology (NIT) Calicut',
  'National Institute of Technology (NIT) Durgapur',
  'National Institute of Technology (NIT) Jaipur',
  'National Institute of Technology (NIT) Nagpur',
  'National Institute of Technology (NIT) Kurukshetra',
  'National Institute of Technology (NIT) Allahabad',
  'National Institute of Technology (NIT) Silchar',
  'National Institute of Technology (NIT) Hamirpur',
  'National Institute of Technology (NIT) Jamshedpur',
  'National Institute of Technology (NIT) Patna',
  'Delhi University (DU)',
  'Guru Gobind Singh Indraprastha University (IPU)',
  'Guru Tegh Bahadur Institute of Technology (GTBIT)',
  'Jamia Millia Islamia University',
  'Jawaharlal Nehru University (JNU)',
  'Ambedkar University Delhi',
  'Birla Institute of Technology and Science (BITS) Pilani',
  'Birla Institute of Technology and Science (BITS) Goa',
  'Birla Institute of Technology and Science (BITS) Hyderabad',
  'Vellore Institute of Technology (VIT) Vellore',
  'Vellore Institute of Technology (VIT) Chennai',
  'Vellore Institute of Technology (VIT) AP',
  'SRM Institute of Science and Technology, Chennai',
  'SRM University, Delhi-NCR',
  'Amity University, Noida',
  'Amity University, Mumbai',
  'Amity University, Kolkata',
  'Banaras Hindu University (BHU)',
  'Aligarh Muslim University (AMU)',
  'Manipal Institute of Technology (MAHE)',
  'Symbiosis International University, Pune',
  'Lovely Professional University (LPU), Phagwara',
  'Chandigarh University',
  'Graphic Era University, Dehradun',
  'Kalinga Institute of Industrial Technology (KIIT) Bhubaneswar',
  'Bharati Vidyapeeth University, Pune',
  'SASTRA Deemed University, Thanjavur',
  'Thapar Institute of Engineering and Technology, Patiala',
  'PES University, Bangalore',
  'BMS College of Engineering, Bangalore',
  'RV College of Engineering, Bangalore',
  'MS Ramaiah Institute of Technology, Bangalore',
  'Bangalore Institute of Technology',
  'Dayananda Sagar College of Engineering, Bangalore',
  'Sir M Visvesvaraya Institute of Technology, Bangalore',
  'Anna University, Chennai',
  'College of Engineering Guindy (CEG), Chennai',
  'PSG College of Technology, Coimbatore',
  'Thiagarajar College of Engineering, Madurai',
  'Coimbatore Institute of Technology',
  'Madras Institute of Technology (MIT), Chennai',
  'Jadavpur University, Kolkata',
  'University of Calcutta',
  'West Bengal University of Technology (MAKAUT)',
  'IIIT Hyderabad (International Institute of Information Technology)',
  'IIIT Delhi (Indraprastha Institute of Information Technology)',
  'IIIT Bangalore',
  'IIIT Allahabad',
  'IIITDM Jabalpur',
  'IIITDM Kancheepuram',
  'Netaji Subhas University of Technology (NSUT) Delhi',
  'Delhi Technological University (DTU)',
  'Indira Gandhi Delhi Technical University for Women (IGDTUW)',
  'Guru Gobind Singh Indraprastha University (GGSIPU) Dwarka',
  'Maharaja Agrasen Institute of Technology, Delhi',
  'Bharati Vidyapeeth College of Engineering, Delhi',
  'Maharaja Surajmal Institute of Technology, Delhi',
  'G. B. Pant Government Engineering College, Delhi',
  'Dr. Akhilesh Das Gupta Institute of Technology & Management, Delhi',
  'University of Mumbai',
  'College of Engineering Pune (COEP)',
  'Veermata Jijabai Technological Institute (VJTI) Mumbai',
  'Sardar Patel College of Engineering, Mumbai',
  'Walchand College of Engineering, Sangli',
  'K. J. Somaiya College of Engineering, Mumbai',
  'Cummins College of Engineering for Women, Pune',
  'MIT World Peace University, Pune',
  'Symbiosis Centre for Engineering, Pune',
  'Osmania University, Hyderabad',
  'University of Hyderabad',
  'Chaitanya Bharathi Institute of Technology (CBIT) Hyderabad',
  'Vasavi College of Engineering, Hyderabad',
  'Gokaraju Rangaraju Institute of Engineering, Hyderabad',
  'Mahatma Gandhi Institute of Technology, Hyderabad',
  'CMR Institute of Technology, Hyderabad',
  'Geethanjali College of Engineering, Hyderabad',
  'Chandigarh College of Engineering and Technology',
  'Punjab Engineering College (PEC) Chandigarh',
  'Guru Nanak Dev Engineering College, Ludhiana',
  'Sant Longowal Institute of Engineering and Technology',
  'Gandaki College of Engineering',
  'Tezpur University, Assam',
  'Assam Engineering College, Guwahati',
  'Jorhat Engineering College, Assam',
  'NIT Arunachal Pradesh',
  'NIT Meghalaya',
  'NIT Manipur',
  'NIT Mizoram',
  'NIT Nagaland',
  'NIT Sikkim',
  'NIT Goa',
  'NIT Puducherry',
  'NIT Uttarakhand',
  'NIT Andhra Pradesh',
  'NIT Tadepalligudem',
  'Shivaji University, Kolhapur',
  'Saurashtra University, Rajkot',
  'Gujarat Technological University (GTU) Ahmedabad',
  'Nirma University, Ahmedabad',
  'Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT)',
  'Institute of Technology, Nirma University',
  'Pondicherry Engineering College',
  'Kerala University of Engineering',
  'College of Engineering Trivandrum (CET)',
  'Government Engineering College, Thrissur',
  'TKM College of Engineering, Kollam',
  'Model Engineering College, Kochi',
  'Rajagiri School of Engineering and Technology, Kochi',
  'Sree Chitra Thirunal College of Engineering, Trivandrum',
  'Visvesvaraya Technological University (VTU) Belgaum',
  'National Institute of Engineering, Mysore',
  'Nitte Meenakshi Institute of Technology, Bangalore',
  'Sri Siddhartha Institute of Technology, Tumkur',
  'Malnad College of Engineering, Hassan',
  'BVB College of Engineering and Technology, Hubli',
  'Sri Jayachamarajendra College of Engineering, Mysore',
  'Ramaiah Institute of Technology, Bangalore',
  'Acharya Institute of Technology, Bangalore',
  'Christ University, Bangalore',
  'Jain University, Bangalore',
  'Alliance University, Bangalore',
  'Presidency University, Bangalore',
  'Punjab University, Chandigarh',
  'Guru Jambheshwar University of Science and Technology, Hisar',
  'Deenbandhu Chhotu Ram University of Science and Technology, Murthal',
  'Maharshi Dayanand University, Rohtak',
  ' Kurukshetra University',
  'Chaudhary Devi Lal University, Sirsa',
  'Guru Nanak Dev University, Amritsar',
  'Punjabi University, Patiala',
  'Sant Baba Bhag Singh University, Jalandhar',
  'CT Institute of Engineering, Jalandhar',
  'Rayat Bahra University, Mohali',
  'Chitkara University, Rajpura',
  'Chandigarh Group of Colleges, Landran',
  'Gulbarga University, Gulbarga',
  'Karnataka University, Dharwad',
  'Tumkur University',
  'Vijayanagara Sri Krishnadevaraya University, Ballari',
  'Kuvempu University, Shimoga',
  'Mangalore University',
  'Mysore University',
  'Mumbai University Institute of Chemical Technology (UDCT)',
  'Shobhaben Pratapbhai Patel School of Pharmacy, Mumbai',
  'Walchand College of Engineering, Solapur',
  'Rajarshi Shahu College of Engineering, Buldana',
  'Yashwantrao Bhonsle College of Engineering, Wardha',
  'Anurag Group of Institutions, Hyderabad',
  'Sri Indu College of Engineering, Hyderabad',
  'Kommuri Pratap Reddy Institute of Technology, Hyderabad',
  'Stanley College of Engineering, Hyderabad',
  'Methodist College of Engineering, Hyderabad',
  'Other / Custom',
];

export const EXPANDED_BRANCH_OPTIONS: string[] = [
  'Computer Science & Engineering',
  'Information Technology',
  'Electronics & Communication',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Artificial Intelligence & Machine Learning',
  'Data Science',
  'Electronics & Electrical Engineering (EEE)',
  'Electronics & Instrumentation Engineering',
  'Electronics & Telecommunication Engineering',
  'Aerospace Engineering',
  'Automobile Engineering',
  'Biotechnology',
  'Biomedical Engineering',
  'Chemical Engineering',
  'Metallurgical Engineering',
  'Mining Engineering',
  'Petroleum Engineering',
  'Agricultural Engineering',
  'Industrial Engineering',
  'Production Engineering',
  'Marine Engineering',
  'Naval Architecture',
  'Textile Engineering',
  'Leather Technology',
  'Food Technology',
  'Pharmaceutical Engineering',
  'Environmental Engineering',
  'Structural Engineering',
  'Architecture',
  'Interior Design',
  'Computer Applications (MCA/BCA)',
  'Business Administration (MBA/BBA)',
  'Other',
];
